config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        public/home#index
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#                admin_root GET    /admin(.:format)                                                                         admin/books#index
#               admin_books GET    /admin/books(.:format)                                                                   admin/books#index
#                           POST   /admin/books(.:format)                                                                   admin/books#create
#            new_admin_book GET    /admin/books/new(.:format)                                                               admin/books#new
#           edit_admin_book GET    /admin/books/:id/edit(.:format)                                                          admin/books#edit
#                admin_book PATCH  /admin/books/:id(.:format)                                                               admin/books#update
#                           PUT    /admin/books/:id(.:format)                                                               admin/books#update
#                           DELETE /admin/books/:id(.:format)                                                               admin/books#destroy
#             admin_authors GET    /admin/authors(.:format)                                                                 admin/authors#index
#                           POST   /admin/authors(.:format)                                                                 admin/authors#create
#          new_admin_author GET    /admin/authors/new(.:format)                                                             admin/authors#new
#         edit_admin_author GET    /admin/authors/:id/edit(.:format)                                                        admin/authors#edit
#              admin_author PATCH  /admin/authors/:id(.:format)                                                             admin/authors#update
#                           PUT    /admin/authors/:id(.:format)                                                             admin/authors#update
#                           DELETE /admin/authors/:id(.:format)                                                             admin/authors#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root 'public/home#index'

  devise_for :users

  namespace :admin do
    root 'books#index'

    resources :books, except: %i[show]
    resources :authors, except: %i[show]
  end
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Author < ApplicationRecord
  has_many :books_and_authors
  has_many :books, through: :books_and_authors, dependent: :destroy

  validates :name,
            presence: true,
            length: { minimum: 5, maximum: 100 }

  default_scope { order(name: :asc) }
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < Admin::AdminController
  before_action :find_author, only: %i[show edit update destroy]

  def index
    @authors = Author.all.page(params[:page])
  end

  def show; end

  def new
    @author = Author.new
  end

  def edit; end

  def create
    @author = Author.new(author_params)

    if @author.save
      flash[:success] = t('admin.authors.new.notifications.successfully_created')
      redirect_to admin_authors_path
    else
      flash.now[:danger] = t('admin.authors.new.notifications.not_created')
      render :new
    end
  end

  def update
    if @author.update(author_params)
      flash[:success] = t('admin.authors.edit.notifications.successfully_updated')
      redirect_to admin_authors_path
    else
      flash.now[:danger] = t('admin.authors.edit.notifications.not_updated')
      render :edit
    end
  end

  def destroy
    if @author.destroy
      flash[:success] = t('admin.authors.destroy.notifications.successfully_deleted')
    else
      flash[:danger] = t('admin.authors.destroy.notifications.not_deleted')
    end
    redirect_to admin_authors_path
  end

  private

  def find_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

app/views/admin/authors/edit.html.slim
/ Variables
- page_title = t('.title')
/
/ / SEO
- title page_title
- noindex false
- nofollow false

/ Beginning

/ Settings
- page_header page_title

.row.justify-content-start
  .col-lg-6
    = render 'admin/authors/common/form', author: @author

app/views/admin/authors/index.html.slim
/ Variables
- page_title = t('.title')
/
/ / SEO
- title page_title
- noindex false
- nofollow false

/ Beginning

/ Settings
- page_header page_title

.mb-4
  = link_to t('public.general.buttons.add'), new_admin_author_path, class: 'btn btn-outline-success'

table.table.mb-0
  thead.thead-inverse
    tr
      th.align-middle.text-nowrap
        = t('admin.authors.index.components.table.header.id')
      th.align-middle.text-nowrap
        = t('admin.authors.index.components.table.header.name')
      th.align-middle.text-nowrap
        = t('admin.authors.index.components.table.header.books')
      th.text-nowrap.text-right
        = t('admin.authors.index.components.table.header.options')
  tbody
    - if @authors.exists?
      - @authors.each do |author|
        tr
          th.align-middle
            = author.id
          td.align-middle
            = author.name
          td.align-middle
            = nice_short_list(author.books, :title)
          td.align-middle.text-right
            => link_to t('admin.authors.index.components.table.body.edit'), edit_admin_author_path(author), class: 'btn btn-outline-primary btn-sm'
            = link_to t('admin.authors.index.components.table.body.delete'), admin_author_path(author), method: :delete, data: { confirm: t('public.general.notifications.are_you_sure') }, class: 'btn btn-outline-danger btn-sm'
    - else
      tr
        td.text-center colspan="4"
          = t('admin.authors.index.components.table.body.no_found')

.mt-5

= paginate @authors

app/views/admin/authors/new.html.slim
/ Variables
- page_title = t('.title')
/
/ / SEO
- title page_title
- noindex false
- nofollow false

/ Beginning

/ Settings
- page_header page_title

.row.justify-content-start
  .col-lg-6
    = render 'admin/authors/common/form', author: @author